name: Auto NBA Scanner Daily Run

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: 

jobs:
  run-scanner:
    runs-on: windows-latest
    steps:
      - name: Clona il codice
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa Librerie
        run: |
          pip install -r requirements.txt
          pip install webdriver-manager

      - name: Avvia il Robot Scanner
        env:
          PYTHONIOENCODING: utf-8
        run: python robot_scanner.py
