name: Auto NBA Scanner Daily Run

on:
  schedule:
    # Esegue ogni giorno alle 13:00 UTC (le 14:00 o 15:00 in Italia a seconda dell'ora legale)
    - cron: '0 5 * * *'
  workflow_dispatch: # Questo ti permette di avviarlo anche a mano con un click se vuoi!

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Clona il codice
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa Chrome e Librerie
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt

      - name: Avvia il Robot Scanner
        run: python robot_scanner.py
